name: AutoPosts.ai CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install UI dependencies
        run: npm install

      - name: Build UI Code
        run: npm run build

      - name: Install Cloud-Functions dependencies
        run: npm install
        working-directory: cloud-api/functions

      - name: Build Cloud Functions
        run: npm run build
        working-directory: cloud-api/functions

      - name: Deploy Cloud Functions
        uses: 'google-github-actions/deploy-cloud-functions@v3'
        timeout-minutes: 10
        with:
         project_id: ${{ secrets.FB_PROJECT_ID}}
         name: 'my-function'
         runtime: 'nodejs22'

      - name: Deploy UI App
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FB_SVC_AC_AUTO_POSTS }}
          channelId: live
          projectId: ${{ secrets.FB_PROJECT_ID}}
