name: AutoPosts.ai UI

on:
  push:
    branches:
      - main
    paths:
      - 'auto-posts-ai.ui/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install UI dependencies
        run: npm run ci
        working-directory: auto-posts-ai.ui

      - name: Build UI Code
        run: npm run build
        working-directory: auto-posts-ai.ui

      - name: Deploy UI App
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FB_SVC_AC_AUTO_POSTS }}
          channelId: live
          projectId: ${{ secrets.FB_PROJECT_ID}}
