name: AutoPosts.ai Core

on:
  push:
    branches:
      - main
    paths:
      - 'auto-posts-ai.core/**'
      - '.github/workflows/core-build.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm run ci
        working-directory: ./auto-posts-ai.core

      - name: Run build
        run: npm run build:prod
        working-directory: ./auto-posts-ai.core

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
